#!/usr/bin/env bash

if [ $# -lt 1 ]; then
  echo "You need to chose a user to apply this to."
  exit 1
fi

if [ "$UID" != "0" ]; then
  echo "You must be root to run this program."
  exit 1
fi

sniffer=$1

groupadd tcpdump
gpasswd -a $sniffer tcpdump
chown $sniffer:tcpdump $(which tcpdump)
chmod 0750 $(which tcpdump)
setcap "CAP_NET_RAW+eip" $(which tcpdump)


